import Head from "next/head";
import Image from "next/image";
import Home from "./home/index";
import Header from "../components/layout/Header";
import Input from "../components/form/Input";
import Reservation from "../components/Reservation";

export default function Index() {
  return (
    <div className="">
      <Head>
        <title>Feane</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Home />
    </div>
  );
}
